apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "onechart.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  {{- with .Values.deployment.labels }}
  labels:
    {{ toYaml . | nindent 4 }}
  {{- else }}
  labels:
    {{ include "onechart.labels" . | nindent 4 }}
  {{- end }}
  {{- with .Values.deployment.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.deployment.autoscaling.enabled }}
  replicas: {{ .Values.deployment.replicas }}
  {{- end }}
  {{- with .Values.deployment.strategy }}
  strategy:
    {{ toYaml . | nindent 2 }}
  {{- end }}
  selector:
    matchLabels:
      {{ include "onechart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.deployment.pod.labels }}
      labels:
        {{ toYaml . | nindent 8 }}
      {{- else }}
      labels:
        {{ include "onechart.selectorLabels" . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.pod.annotations }}
      annotations:
        {{ toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.deployment.pod.securityContext }}
      securityContext:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.pod.imagePullSecrets }}
      imagePullSecrets:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ if .Values.serviceAccount.create }}{{ include "onechart.fullname" . }}{{ else }}{{ .Values.serviceAccount.name }}{{ end }}
      restartPolicy: {{ .Values.deployment.pod.restartPolicy }}
      dnsPolicy: {{ .Values.deployment.pod.dnsPolicy }}
      hostNetwork: {{ .Values.deployment.pod.hostNetwork }}
      {{- if .Values.deployment.pod.shareProcessNamespace }}
      shareProcessNamespace: true
      {{- end }}

      {{- with .Values.deployment.pod.initContainers }}
      initContainers:
        {{ toYaml . | nindent 8 }}
      {{- end }}

      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.deployment.pod.containers.main.image.repository }}:{{ .Values.deployment.pod.containers.main.image.tag }}"
          imagePullPolicy: {{ .Values.deployment.pod.containers.main.image.pullPolicy }}
          {{- with .Values.deployment.pod.containers.main.securityContext }}
          securityContext:
            {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.pod.containers.main.envFrom }}
          envFrom:
            {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.pod.containers.main.env }}
          env:
            {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.pod.containers.main.ports }}
          ports:
            {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.pod.containers.main.livenessProbe }}
          livenessProbe:
            {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.pod.containers.main.readinessProbe }}
          readinessProbe:
            {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.pod.containers.main.resources }}
          resources:
            {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.pod.containers.main.volumeMounts }}
          volumeMounts:
            {{ toYaml . | nindent 12 }}
          {{- end }}

        {{- range .Values.deployment.pod.sidecars }}
        - name: {{ .name }}
          image: {{ .image }}
          {{- with .imagePullPolicy }}
          imagePullPolicy: {{ . }}
          {{- end }}
          {{- with .env }}
          env:
            {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .ports }}
          ports:
            {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .volumeMounts }}
          volumeMounts:
            {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .resources }}
          resources:
            {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .securityContext }}
          securityContext:
            {{ toYaml . | nindent 12 }}
          {{- end }}
        {{- end }}

      {{- with .Values.deployment.pod.volumes }}
      volumes:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.pod.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.pod.affinity }}
      affinity:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.pod.tolerations }}
      tolerations:
        {{ toYaml . | nindent 8 }}
      {{- end }}
