{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "onechart.fullname" . }}-external
spec:
  # how often to refresh from the remote store
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  # which SecretStore or ClusterSecretStore to use
  secretStoreRef:
    name: {{ .Values.externalSecrets.storeRef.name }}
    kind: {{ .Values.externalSecrets.storeRef.kind }}
  # the resulting k8s Secret that will be created
  target:
    name: {{ include "onechart.fullname" . }}-secret
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        annotations:
          reloader.stakater.com/match: "true"
  # mappings of keys in the k8s Secret -> remote secret locations
  data:
{{- range .Values.externalSecrets.data }}
    - secretKey: {{ .secretKey | quote }}
      remoteRef:
        key: {{ .remoteRef.key | quote }}
        {{- if .remoteRef.property }}
        property: {{ .remoteRef.property | quote }}
        {{- end }}
{{- end }}
{{- end }}
