{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "onechart.fullname" . }}-ext
  namespace: {{ .Values.namespace.name }}
  {{- with .Values.externalSecrets.labels }}
  labels:
    {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.externalSecrets.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.storeRef.name }}
    kind: {{ .Values.externalSecrets.storeRef.kind }}
  target:
    name: {{ include "onechart.fullname" . }}-secret
    creationPolicy: Owner
    template:
      metadata:
        {{- with .Values.externalSecrets.annotations }}
        annotations:
          {{ toYaml . | nindent 10 }}
        {{- end }}
      type: {{ .Values.externalSecrets.targetType  | default "Opaque" }}
  data:
{{ toYaml .Values.externalSecrets.data | indent 4 }}
{{- end }}
