{{- if .Values.virtualService.enabled }}
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ include "onechart.fullname" . }}-virtual-service
  annotations:
{{ toYaml .Values.virtualService.annotations | indent 4 }}
spec:
  hosts:
{{ toYaml .Values.virtualService.hosts | indent 4 }}
  gateways:
{{ toYaml .Values.virtualService.gateways | indent 4 }}
  http:
{{- range .Values.virtualService.http }}
    - match:
        - uri:
            prefix: {{ quote .match.uri.prefix }}
      route:
        - destination:
            host: {{ .route.destination.host }}.{{ $.Release.Namespace }}.svc.cluster.local
            port:
              number: {{ .route.destination.port }}
      timeout: {{ .timeout }}
      retries:
        attempts: {{ .retries.attempts }}
        perTryTimeout: {{ .retries.perTryTimeout }}
{{- end }}
{{- end }}
