apiVersion: v1
kind: Namespace
metadata:
  labels:
    {{- if .Values.istio.enabled }}
    istio.io/dataplane-mode: ambient
    {{- end }}
    do-docker-credentials-secret: "true"
  name: {{ .Values.namespace }}
