apiVersion: v1
kind: Service
metadata:
  name: {{ include "onechart.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  {{- with .Values.service.labels }}
  labels:
    {{ toYaml . | nindent 4 }}
  {{- else }}
  labels:
    {{ include "onechart.labels" . | nindent 4 }}
  {{- end }}
  {{- with .Values.service.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{ include "onechart.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
