{{- if .Values.statuspage.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: uptime-status-{{ include "onechart.fullname" . }}
  labels:
    status.io/enabled: "true"
  annotations:
    reloader.stakater.com/match: "true"
data:
  config.yaml: |-
{{- /*
       Use toYaml to serialize a map with one key: "endpoints",
       whose value is the array from .Values.statuspage.endpoints.
       Then indent it 4 spaces so that it becomes:

         endpoints:
           - name: ...
             group: ...
             …
           - name: ...
             …
*/}}
{{ toYaml (dict "endpoints" .Values.statuspage.endpoints) | indent 4 }}
{{- end }}
