{{- if .Values.virtualService.enabled }}
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ include "onechart.fullname" . }}-vs
  namespace: {{ .Values.namespace.name }}
  {{- with .Values.virtualService.labels }}
  labels:
    {{ toYaml . | nindent 4 }}
  {{- else }}
  labels:
    {{ include "onechart.labels" . | nindent 4 }}
  {{- end }}
  {{- with .Values.virtualService.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  hosts:
{{ toYaml .Values.virtualService.hosts | indent 4 }}
  gateways:
{{ toYaml .Values.virtualService.gateways | indent 4 }}
  http:
{{ toYaml .Values.virtualService.http | indent 4 }}
{{- end }}
